### ISSUE TITLE
FAB auf Meeting-Detail-Page anpassen

### ISSUE THREAD

**Issue by FabianWilms** [peter-mueller/weisswurstverwaltung#14]
Durch die neue Möglichkeit der Nutzer-Registrierung muss der FAB nun angepasst werden.
Wenn der Nutzer nicht im meeting vorhanden ist, soll der Button zum eintragen genutzt werden können. Ist der Nutzer bereits eingetragen, soll der FAB zum verlassen des Meetings benutzt werden. Damit wird dann auch verhindert, dass ein Nutzer sich mehrfach einträgt.

https://github.com/peter-mueller/weisswurstverwaltung/blob/master/app/elements/meeting-detail-page/meeting-detail-page.html#L70

**Comment by FabianWilms** [comment]
@peter-mueller mittwoch ist release. keine ausreden mehr xD

**Comment by peter-mueller** [comment]
Das user Object von firebase-auth hat keinen usernamen. In der order soll der user mit der uid gespeichert werden, aber was soll dann als namen angezeigt werden?

**Comment by FabianWilms** [comment]
Das ist ja schon drin

**Comment by FabianWilms** [comment]
Es wird user.Detail.user.password.email gespeichert. Ich wollte das aber noch anpassen, dass mana siich das erste "user.detail" sparen kann. Liegt ja nur daran wie ich es aus dem wwm-auth rausschicke

**Comment by FabianWilms** [comment]
https://github.com/peter-mueller/weisswurstverwaltung/blob/master/app/elements/meeting-detail-page/meeting-detail-page.html#L86

**Comment by peter-mueller** [comment]
```
_togglePerson: function () {
          if (!this.meeting.orders) {
            this.meeting.orders = [];
          }

          var index = this.meeting.orders.map(function(order) {return order.uid;}).indexOf(this.user.uid);
          if (index == -1) {
            this.push('meeting.orders', {name: this.user.password.email, uid: this.user.uid, brezen: 0, weisswurst: 0});
          } else {
            this.splice('meeting.orders', index, 1);
          }
        },
```

**Comment by FabianWilms** [comment]
Dann hat der FAB aber durchgehend das gleiche aussehe, oder?

**Comment by peter-mueller** [comment]
Das mach ich _theoretisch_ unabhängig von dieser Funktion

**Comment by FabianWilms** [comment]
👍👍👍

Peter Müller notifications@github.com schrieb am Di., 1. Dez. 2015 20:46:

**Comment by FabianWilms** [comment]
ist erledigt!
