### ISSUE TITLE
Aktueller Nutzer in der Toolbar

### ISSUE THREAD

**Issue by FabianWilms** [peter-mueller/weisswurstverwaltung#16]
https://github.com/peter-mueller/weisswurstverwaltung/blob/master/app/elements/wwm-auth/wwm-auth.html#L50

Der aktuell angemeldete Nutzer sollte oben rechts in der Toolbar angezeigt werden. Am besten auch mit einem User-Avatar-Element und einem dropdown, über welches sich der nutzer abmelden kann. Gerne aber auch andere vorschläge :wink: 

@peter-mueller Milestone? 2.0 ist diesen Sonntag dran. Kannst du ja mal festlegen.

**Comment by peter-mueller** [comment]
Kann man glaub ganz gut mit #15 zusammen machen

**Comment by FabianWilms** [comment]
https://github.com/peter-mueller/weisswurstverwaltung/commit/d42991272c7aa32872b7517c5ea0558853007c23
