### ISSUE TITLE
Eintrag vom jemandenen anlegen, der kein User ist.

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/weisswurstverwaltung#17]
Eine große Verbesserung wäre, wenn man Einträge vom Leuten angeben könnte, die keine (oder noch keine) User dieses Systems sind - z.B. aus Präsentationsgründen - dazu müsste noch geklärt werden wer diese Einträge bearbeiten kann.

**Comment by FabianWilms** [comment]
- Variante 1

Solche Einträge können nur einmalig erstellt werden. Also anschließend nicht mehr geändert.
- Variante 2

Alle können diese Einträge bearbeiten.
- Variante 3

Nur die Admins, die auch Bestellungen als bezahtl markieren können, dürfen diese bearbeiten.

**Comment by FabianWilms** [comment]
https://github.com/cwdoh/paper-fab-menu @peter-mueller :question:

**Comment by FabianWilms** [comment]
Beim erstellen eines meetings wird nun der ersteller automatisch hinzugefügt. als ersteller kann man sich nicht aus seinem eigenen meeting mehr austragen. dafür erscheint ein button zum hinzufügen von gästen. Die Bestellung von gästen kann nur vom ersteller des meetings und den admins angepasst werden. löschen eines gastes ist noch nicht implementiert.
