### ISSUE TITLE
Der Nutzer kann seine Kosten sehen

### ISSUE THREAD

**Issue by darenegade** [peter-mueller/weisswurstverwaltung#22]
Erklärt sich selbst

**Comment by FabianWilms** [comment]
https://github.com/peter-mueller/weisswurstverwaltung/commit/963a2638b9276a93862f9edc92f1079d2cad6427

**Comment by darenegade** [comment]
An Samstag Abend werden hier noch Tickets bearbeitet. Sauber 

Von meinem iPhone gesendet

**Comment by FabianWilms** [comment]
Sagt doch alles über mein Leben aus :cry:

**Comment by darenegade** [comment]
Vielleicht musst du doch mal die Kinder in die Obhut deiner Freundin geben und mit uns auf Achse gehen 😄

**Comment by FabianWilms** [comment]
Solange ich am nächsten Tag um 5 Uhr aufstehen darf wird das leider erstmal nix 😛
