### ISSUE TITLE
Detail-View für Meeting

### ISSUE THREAD

**Issue by FabianWilms** [peter-mueller/weisswurstverwaltung#4]
Bei Klick auf ein Meeting in der Liste soll zur Detail-Ansicht dieses Meetings navigiert werden. In dieser Ansicht wird unter dem Übersichts-Item des Meetings die einzelnen Bestellungen einsehbar sein und außerdem neue Bestellungen erzeugt werden können.

**Comment by FabianWilms** [comment]
@peter-mueller Wenn über die ID des meetings navigiert werden soll, wie soll ich das im aktuellen Stand umsetzen? Das aktuelle Meeting-Objekt hat noch keine ID. soll ich diese einfach hinzufügen oder solange übers datum gehen?

**Comment by peter-mueller** [comment]
Sry, die ids hab ich noch nicht reingemacht.

Mit firebase schaut dass dann so aus: 

``` json
[
    {
      "author" : "Hallp",
      "date" : 1446226846745,
      "message" : "1",
     "__firebaseKey__": "-K1tpaOeqIiuXe1ZzoEF" 
    },
...

]
```

Evtl. geht das auch nicht mit iron-list :(

**Comment by FabianWilms** [comment]
Geht nicht wegen dem Onclick? Oder weshalb?

**Comment by peter-mueller** [comment]
So müsste es jetzt doch gehen :)

**Comment by FabianWilms** [comment]
done!
