### ISSUE TITLE
NO-ROBOTS

### ISSUE THREAD

**Issue by darenegade** [peter-mueller/weisswurstverwaltung#43]
Google crawled die WW-Verwaltung. Das ist nicht so geil

**Comment by FabianWilms** [comment]
@peter-mueller muss eine User-Page erstellen (https://help.github.com/articles/user-organization-and-project-pages/) und dort eine robots.txt mit folgendem Inhalt erstellen:

```
User-agent: *
Disallow: /
```

Wenn ich die Datei in das Repo hier schmeiße bringt das quasi nichts. Oder @peter-mueller schiebt das Repo zu Weisswurstsystems, dann können wirs auf die Organization-Page packen.

**Comment by peter-mueller** [comment]
Habs verschoben

**Comment by FabianWilms** [comment]
Dank je vel!

**Comment by FabianWilms** [comment]
https://weisswurstsystems.github.io/robots.txt

**Comment by darenegade** [comment]
Top danke
