### ISSUE TITLE
Userregistrierung und Bestellung automatisch User zuordnen

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/weisswurstverwaltung#7]

**Comment by FabianWilms** [comment]
Man soll sich auf der Seite mit mail, password und nutzernamen registrieren können. ein nutzer-objekt sieht nachher so aus

``` JSON
{
    "mail": "<mail>",
    "password": "<hash>",
    "name": "<username>",
    "color": "<hex>",
    "preference_weisswürste": "<value>",
    "preference_brezen": "<value>"
}
```

Für Milestone 2.0 werden die letzten drei werte zunächst nur mit defaults initialisiert, nutzerverwaltung folgt in milestone 3.0.
Als Nutzer kann man sich anschließend in meetings eintragen. Für jeden nutzer wird im meeting eine order mit seinem namen und den preferences initialisiert. Die bestell-werte kann der nutzer verändern. Wenn ein nutzer sich aus dem meeting austrägt verschwindet auch seine bestellung.

**Comment by peter-mueller** [comment]
User brauchen unbedingt ein Feld claus: true/false

**Comment by FabianWilms** [comment]
zum teste kann der testnutzer `hans@test.de` mit dem passwort `test`verwendet werden. natürlich kann man sich auch registrieren.

**Comment by FabianWilms** [comment]
https://github.com/peter-mueller/weisswurstverwaltung/commit/9ab3a5ce90dd354ba3856f69c81cbfd072510334

https://github.com/peter-mueller/weisswurstverwaltung/commit/7d744415efad52e93641f084f6345e3a5cfe4458

https://github.com/peter-mueller/weisswurstverwaltung/commit/ae7c953d41755cb167e41fe4d27635b4bca3ca2e

https://github.com/peter-mueller/weisswurstverwaltung/commit/20f3c24c04b4448f943d75d9351ca1aaf9498269

https://github.com/peter-mueller/weisswurstverwaltung/commit/bb671244aad58c34173ebd67268213838a6cfc36
